"""add updated_at field

Revision ID: 2643e91e242f
Revises: e5b47b081321
Create Date: 2021-04-27 17:02:46.071027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643e91e242f'
down_revision = 'e5b47b081321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'todos', ['uuid'])
    op.drop_column('todos', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('timestamp', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'todos', type_='unique')
    op.drop_column('todos', 'uuid')
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
